export { default as HomePage } from './home/HomePage'
export { default as TasksPage } from './tasks/TasksPage'
export { default as TaskForm } from './tasks/TaskForm'
export { default as NotFoundPage } from './notFound/NotFoundPage'
export { default as LoginPage } from './login/LoginPage'
export { default as SignUpPage } from './login/SignUpPage'
export { default as ProfilePage } from './profile/ProfilePage'
export { default as AboutPage } from './about/AboutPage'
